name: ecommerce_analytics
version: '1.0.0'
require-dbt-version: [">=1.12.0", "<3.0.0"]

profile: ecommerce_analytics

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  ecommerce_analytics:
    +schema: raw

models:
  ecommerce_analytics:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table

data_tests:
  ecommerce_analytics:
    +severity: warn
flags:
  require_generic_test_arguments_property: true