USE ROLE ACCOUNTADMIN;

-- Grant schema creation rights on RAW_DB
GRANT CREATE SCHEMA ON DATABASE RAW_DB TO ROLE DBT_ROLE;

-- Grant usage and management rights across schemas
GRANT USAGE, CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE RAW_DB TO ROLE DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON FUTURE SCHEMAS IN DATABASE RAW_DB TO ROLE DBT_ROLE;